/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasaAiRouteImport } from './routes/casa-ai'
import { Route as DesignersRouteImport } from './routes/designers'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as StylesRouteImport } from './routes/styles'
import { Route as DesignsDesignIdRouteImport } from './routes/designs/$designId'
import { Route as HomesIndexRouteImport } from './routes/homes/index'
import { Route as HomesTypeRouteImport } from './routes/homes/$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasaAiRoute = CasaAiRouteImport.update({
  id: '/casa-ai',
  path: '/casa-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignersRoute = DesignersRouteImport.update({
  id: '/designers',
  path: '/designers',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesRoute = StylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsDesignIdRoute = DesignsDesignIdRouteImport.update({
  id: '/designs/$designId',
  path: '/designs/$designId',
  getParentRoute: () => rootRouteImport,
} as any)
const HomesIndexRoute = HomesIndexRouteImport.update({
  id: '/homes/',
  path: '/homes/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomesTypeRoute = HomesTypeRouteImport.update({
  id: '/homes/$type',
  path: '/homes/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casa-ai': typeof CasaAiRoute
  '/designers': typeof DesignersRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/spaces': typeof SpacesRoute
  '/styles': typeof StylesRoute
  '/designs/$designId': typeof DesignsDesignIdRoute
  '/homes/$type': typeof HomesTypeRoute
  '/homes/': typeof HomesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casa-ai': typeof CasaAiRoute
  '/designers': typeof DesignersRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/spaces': typeof SpacesRoute
  '/styles': typeof StylesRoute
  '/designs/$designId': typeof DesignsDesignIdRoute
  '/homes/$type': typeof HomesTypeRoute
  '/homes': typeof HomesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/casa-ai': typeof CasaAiRoute
  '/designers': typeof DesignersRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/spaces': typeof SpacesRoute
  '/styles': typeof StylesRoute
  '/designs/$designId': typeof DesignsDesignIdRoute
  '/homes/$type': typeof HomesTypeRoute
  '/homes/': typeof HomesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/casa-ai'
    | '/designers'
    | '/favorites'
    | '/login'
    | '/spaces'
    | '/styles'
    | '/designs/$designId'
    | '/homes/$type'
    | '/homes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/casa-ai'
    | '/designers'
    | '/favorites'
    | '/login'
    | '/spaces'
    | '/styles'
    | '/designs/$designId'
    | '/homes/$type'
    | '/homes'
  id:
    | '__root__'
    | '/'
    | '/casa-ai'
    | '/designers'
    | '/favorites'
    | '/login'
    | '/spaces'
    | '/styles'
    | '/designs/$designId'
    | '/homes/$type'
    | '/homes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasaAiRoute: typeof CasaAiRoute
  DesignersRoute: typeof DesignersRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  SpacesRoute: typeof SpacesRoute
  StylesRoute: typeof StylesRoute
  DesignsDesignIdRoute: typeof DesignsDesignIdRoute
  HomesTypeRoute: typeof HomesTypeRoute
  HomesIndexRoute: typeof HomesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casa-ai': {
      id: '/casa-ai'
      path: '/casa-ai'
      fullPath: '/casa-ai'
      preLoaderRoute: typeof CasaAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designers': {
      id: '/designers'
      path: '/designers'
      fullPath: '/designers'
      preLoaderRoute: typeof DesignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles': {
      id: '/styles'
      path: '/styles'
      fullPath: '/styles'
      preLoaderRoute: typeof StylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/$designId': {
      id: '/designs/$designId'
      path: '/designs/$designId'
      fullPath: '/designs/$designId'
      preLoaderRoute: typeof DesignsDesignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homes/': {
      id: '/homes/'
      path: '/homes'
      fullPath: '/homes/'
      preLoaderRoute: typeof HomesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homes/$type': {
      id: '/homes/$type'
      path: '/homes/$type'
      fullPath: '/homes/$type'
      preLoaderRoute: typeof HomesTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasaAiRoute: CasaAiRoute,
  DesignersRoute: DesignersRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  SpacesRoute: SpacesRoute,
  StylesRoute: StylesRoute,
  DesignsDesignIdRoute: DesignsDesignIdRoute,
  HomesTypeRoute: HomesTypeRoute,
  HomesIndexRoute: HomesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
